series: Bufferless Rendering
title: Rendering a Heightmap
author:
  name: Joshua Alway
  email: 
  github: https://github.com/IGME-RIT
description: Render a Heightmap from a texture.
language: C++
tags:
  - Graphics
extra_resources:
connections:
  - series: Bufferless Rendering
    title: Rendering Geometry Procedurally
  - series: Basic OpenGL with GLFW
    title: Textures